### ISSUE TITLE
haaretz found a way to detect the add on and block access to the site

### ISSUE THREAD

**Issue by xspy007** [yuvadm/free-haaretz#28] opened 2018-08-22 14:50 UTC
Hey

pls check haaretz.  they are preventing from any use unless u disable the free haaretz add on.

Pls solve it as soon as possible,  this is one of the best.

Udi

**Comment by yuvadm** [comment] 2018-08-22 15:00
Duplicate of #27

**Closed as completed by yuvadm** 2018-08-22 15:00 UTC
